# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    #module = bld.create_ns3_module('olsr-with-dsa', ['core'])
    module = bld.create_ns3_module('olsr-with-dsa', ['internet'])
    module.includes = '.'
    module.source = [
        'model/olsr-with-dsa-header.cc',
        'model/olsr-with-dsa-routing-protocol.cc',
        'model/olsr-with-dsa-state.cc',
        'helper/olsr-with-dsa-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('olsr-with-dsa')
    module_test.source = [
        'test/olsr-with-dsa-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'olsr-with-dsa'
    headers.source = [
        'model/olsr-with-dsa-header.h',
        'model/olsr-with-dsa-repositories.h',
        'model/olsr-with-dsa-routing-protocol.h',
        'model/olsr-with-dsa-state.h',
        'helper/olsr-with-dsa-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

