# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('olsr-with-dsa-example', ['olsr-with-dsa'])
    obj.source = 'olsr-with-dsa-example.cc'

